cluster: "local"

global:
  commonAnnotations:
    cluster: "local"

kps:
  fullnameOverride: kps
  alertmanager:
    fullnameOverride: alertmanager

  prometheusOperator:
    fullnameOverride: prometheus-operator
    scrapeInterval: 15s
    evaluationInterval: 15s

  prometheus:
    fullnameOverride: prometheus
    ingress:
      enabled: false  # We'll use IngressRoute instead

  kube-state-metrics:
    fullnameOverride: kube-state-metrics

  prometheus-node-exporter:
    fullnameOverride: node-exporter

  grafana:
    fullnameOverride: grafana
    ingress:
      enabled: false  # We'll use IngressRoute instead
    admin:
      existingSecret: "grafana-admin-secret"
      userKey: admin
      passwordKey: password