cluster: "local"

global:
  commonAnnotations:
    cluster: "local"

kps:
  fullnameOverride: kps
  alertmanager:
    fullnameOverride: alertmanager
  version: "66.2.2"

  prometheusOperator:
    fullnameOverride: prometheus-operator
    scrapeInterval: 15s
    evaluationInterval: 15s

  prometheus:
    fullnameOverride: prometheus
    ingress:
      enabled: false

  kube-state-metrics:
    fullnameOverride: kube-state-metrics

  prometheus-node-exporter:
    fullnameOverride: node-exporter

  grafana:
    fullnameOverride: grafana
    ingress:
      enabled: false