cluster: "local"

global:
  commonAnnotations:
    cluster: "local"

kps:
  fullnameOverride: kps
  alertmanager:
    fullnameOverride: alertmanager
  version: "66.2.2"

  prometheusOperator:
    fullnameOverride: prometheus-operator
    scrapeInterval: 15s
    evaluationInterval: 15s
    tls:
        enabled: true
    admissionWebhooks:
        enabled: true

  prometheus:
    fullnameOverride: prometheus
    ingress:
      enabled: false

  kube-state-metrics:
    fullnameOverride: kube-state-metrics

  prometheus-node-exporter:
    fullnameOverride: node-exporter

  grafana:
    fullnameOverride: grafana
    ingress:
      enabled: false
    adminPassword: ""
    envFromSecret: "grafana-admin-secret"

    grafana.ini:
        security:
        admin_user: admin
        admin_password: "$GRAFANA_ADMIN_PASSWORD"

    extraSecretMounts:
        - name: grafana-admin-secret
          secretName: grafana-admin-secret
          defaultMode: 0440
          mountPath: /etc/secrets/grafana
          readOnly: true