cluster: "local"

loki-stack:
  fullnameOverride: loki-stack
  loki:
    fullnameOverride: loki
    auth_enabled: false
    serviceMonitor:
      enabled: true
  promtail:
    fullnameOverride: promtail
    daemonset:
      enabled: true
    config:
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
      clients:
        - url: http://loki.local.eryx.pro/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: nodes
          static_configs:
            - targets:
                - localhost
              labels:
                job: system-logs
                __path__: /var/log/**/*.log

    serviceMonitor:
      enabled: true
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
        readOnly: true
