cluster: "local"

loki-stack:
  fullnameOverride: loki-stack
  loki:
    fullnameOverride: loki
    auth_enabled: false
    serviceMonitor:
      enabled: true
  promtail:
    fullnameOverride: promtail
    serviceMonitor:
      enabled: true
