apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 900
  template:
    spec:
      serviceAccountName: vault
      containers:
      - name: vault-init
        image: "hashicorp/vault:1.18.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          echo "Waiting for Vault to start..."
          until vault status 2>&1 | grep "Sealed.*true" > /dev/null; do
            sleep 5
          done
          
          echo "Checking initialization status..."
          if ! vault status | grep -q "Initialized.*true"; then
            echo "Initializing Vault..."
            vault operator init -key-shares=1 -key-threshold=1 -format=json > /vault/data/init.json
            
            # Extract unseal key and root token
            UNSEAL_KEY=$(cat /vault/data/init.json | jq -r '.unseal_keys_b64[0]')
            
            echo "Unsealing Vault..."
            vault operator unseal $UNSEAL_KEY
          else
            echo "Vault already initialized"
          fi
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: data-vault-0
      restartPolicy: OnFailure