apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 900
  template:
    spec:
      serviceAccountName: vault
      containers:
      - name: vault-init
        image: "hashicorp/vault:1.18.1"
        imagePullPolicy: IfNotPresent
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        command:
        - /bin/sh
        - -c
        - |
          set -e
          
          # Wait for Vault to be available
          echo "Waiting for Vault to start..."
          until vault status > /dev/null 2>&1; do
            echo "Waiting for Vault to be available..."
            sleep 5
          done
          
          # Check initialization status
          if vault status | grep -q "Initialized.*false"; then
            echo "Initializing Vault..."
            vault operator init -key-shares=1 -key-threshold=1 -format=json > /vault/data/init.json
            
            # Extract unseal key
            UNSEAL_KEY=$(grep -o '"unseal_keys_b64":\[[^]]*\]' /vault/data/init.json | grep -o '"[^"]*"' | tail -n1 | tr -d '"')
            
            echo "Unsealing Vault..."
            vault operator unseal $UNSEAL_KEY
            
            echo "Initialization and unseal complete"
          else
            echo "Vault is already initialized"
            
            # Check if sealed
            if vault status | grep -q "Sealed.*true"; then
              echo "Vault is sealed, attempting to unseal..."
              UNSEAL_KEY=$(grep -o '"unseal_keys_b64":\[[^]]*\]' /vault/data/init.json | grep -o '"[^"]*"' | tail -n1 | tr -d '"')
              vault operator unseal $UNSEAL_KEY
            fi
          fi
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: data-vault-0
      restartPolicy: OnFailure