apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: {{ include "cluster-common.hostname" . }}
    annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: le-production
spec:
    entryPoints:
        - websecure
    routes:
        - kind: Rule
          match: Host(`{{ include "cluster-common.hostname" . }}`)
          middlewares:
              - name: traefik-dashboard-basicauth
                namespace: traefik
          priority: 10
          services:
              - kind: TraefikService
                name: api@internal
    tls:
        enabled: true
        secretName: {{ include "cluster-common.secretName" . }}
