apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.traefik.fullnameOverride }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: le-production
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ include "traefik.hostname" . }}`)
      middlewares:
        - name: traefik-dashboard-basicauth
          namespace: traefik
      priority: 10
      services:
        - kind: TraefikService
          name: api@internal
  tls:
    secretName: {{ include "traefik.secretname" . }}
