---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dns-token-secret
spec:
  provider: vault
  parameters:
    roleName: "csi-secrets-store"
    vaultAddress: https://vault.local.eryx.pro
    vaultKubernetesMountPath: kubernetes/home
    objects: |
      - objectName: "kv"
        secretKey: "cloudflare"
        secretPath: "kv/dns-zone"
  secretObjects:
    - type: Opaque
      secretName: kv
      data:
        - key: cloudflare
          objectName: kv
---