cluster: "local"

vault:
  server:
    enabled: true
    image:
      repository: "vault"
      tag: "1.13.3"
      pullPolicy: IfNotPresent
    readinessProbe:
      enabled: false
    extraArgs: >
      --tls-skip-verify
      --enable-auth=kubernetes
  auth:
    kubernetes:
      enabled: true
      config:
        token_reviewer_jwt_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_host: https://kubernetes.default.svc
        kubernetes_ca_cert_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  policies:
    - name: cert-manager
      rules: |
        path "secret/data/cert-manager/*" {
          capabilities = ["read"]
        }
  dataStorage:
    storageClass: file
  ui:
    enabled: true
  csi:
    enabled: true
  injector:
    enabled: true
