apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/prometheus: https://prometheus.{{ .Values.cluster }}.eryx.pro
    link.argocd.argoproj.io/grafana: https://grafana.{{ .Values.cluster }}.eryx.pro
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: cluster-critical/kube-prometheus-stack
    repoURL: https://github.com/omer-bar/Homelab
    targetRevision: HEAD
    helm:
      skipCrds: true  # Skip CRDs here as they're handled by the CRD application
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true