apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-admin-token
  namespace: monitoring
spec:
  provider: vault
  secretObjects:
  - secretName: grafana-admin-secret
    type: Opaque
    data:
    - objectName: grafana-admin-password
      key: password
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "csi-secrets-store"
    objects: |
      - objectName: "grafana-admin-password"
        secretPath: "secret/data/grafana/admin"
        secretKey: "password"