apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-dashboard
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ include "cluster-common.hostname" . }}`)
      services:
        - name: grafana
          port: 80
  tls:
    secretName: {{ include "cluster-common.secretName" . }}
