---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: omerbar7193@gmail.com
    privateKeySecretRef:
      name: le-production
    solvers:
      - dns01:
          cloudflare:
            email: omerbad7193@gmail.com
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "eryx.pro"
