---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: dns-token-secret
    namespace: cert-manager
spec:
    provider: vault
    parameters:
        roleName: "csi-secrets-store"
        vaultAddress: https://vault.local.eryx.pro/
        vaultKubernetesMountPath: kubernetes/home
        objects: |
            - objectName: "cloudflare"
              secretKey: "cloudflare"
              secretPath: "kv-2/data/dns-zone"
              secretVersion: "latest"
    secretObjects:
        - type: Opaque
          secretName: cloudflare-token-secret
          data:
              - key: cloudflare-token
                objectName: cloudflare
---

