apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  provider: vault
  secretObjects:
  - secretName: cloudflare-token-secret
    type: Opaque
    data:
    - objectName: cloudflare-token
      key: cloudflare-token
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    vaultNamespace: "kube-system"
    roleName: "csi-secrets-store"
    objects: |
      - objectName: "cloudflare-token"
        secretPath: "secret/data/cert-manager/cloudflare-token"
        secretKey: "token"