apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  namespace: cert-manager
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"    # Added .svc suffix
    vaultSkipTLSVerify: "true"
    roleName: "csi-secrets-store"
    useTokenReview: "true"                         # Added this
    vaultKubernetesMountPath: "kubernetes"         # Added this
    objects: |
      - objectName: cloudflare-token
        objectType: secret
        objectPath: secret/data/cert-manager/cloudflare-token