apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  namespace: cert-manager
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault:8200"    # Changed to use in-cluster DNS name
    vaultSkipTLSVerify: "true"
    roleName: "csi-secrets-store"
    objects: |
      - objectName: cloudflare-token
        objectType: secret
        objectPath: secret/data/cert-manager/cloudflare-token