apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  namespace: cert-manager
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.local.eryx.pro:8200"
    vaultSkipTLSVerify: "true"
    roleName: "csi-secrets-store-sa"
    objects: |
      - objectName: cloudflare-token
        objectType: secret
        objectPath: secret/cert-manager/cloudflare-token