apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dns-token-secret
  namespace: cert-manager
spec:
  provider: vault
  parameters:
    roleName: "csi-secrets-store"
    vaultAddress: "http://vault.local.eryx.pro"
    vaultKubernetesMountPath: "kubernetes/home"
    objects: |
      - objectName: "cert-manager/cloudflare-token"
        secretKey: "cloudflare-token"
        secretPath: "secret/data/cert-manager/cloudflare-token"
        objectType: "kv2"
  secretObjects:
    - secretName: cloudflare-token-secret
      type: Opaque
      data:
        - key: cloudflare-token
          objectName: "token"
