apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secrets
  namespace: cert-manager
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    vaultSkipTLSVerify: "true"
    roleName: "csi-secrets-store"
    vaultKubernethesAuthPath: "kubernetes"
    objects: |
      - objectName: "cloudflare-token"
        secretPath: "secret/data/cert-manager/cloudflare-token"
        secretKey: "token"
        secretArgs:    # Added these to specify exactly what we want
          path: "secret/data/cert-manager/cloudflare-token"
          method: "GET"