# argocd/certificate.yaml
{{- $hostname := include "argocd.hostname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: {{ include "argocd.secretname" . }}
  issuerRef:
    name: le-production
    kind: ClusterIssuer
  commonName: {{ $hostname }}
  dnsNames:
    - {{ $hostname }}