apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: {{ include "argocd.secretname" . }}
  issuerRef:
    name: le-production
    kind: ClusterIssuer
  commonName: "*.{{ .Values.cluster }}.eryx.pro"
  dnsNames:
    - "{{ .Values.cluster }}.eryx.pro"
    - "*.{{ .Values.cluster }}.eryx.pro"