apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.priority: "10"
        cert-manager.io/cluster-issuer: le-production
        traefik.ingress.kubernetes.io/custom-response-headers: "Access-Control-Allow-Origin:*||Access-Control-Allow-Methods:GET,POST,OPTIONS||Access-Control-Allow-Headers:DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range||Access-Control-Expose-Headers:Content-Length,Content-Range"
    labels:
        app: loki
    name: loki
    namespace: monitoring
spec:
    rules:
        - host: loki.local.eryx.pro
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: loki
                            port:
                                number: 3100
    tls:
        - secretName: eryx-pro-tls
          hosts: [loki.local.eryx.pro]
